import type { Metadata } from 'next'
import './globals.css'
import StyledComponentsRegistry from "@/lib/antdRegistry";


export const metadata: Metadata = {
  title: 'report-online',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={'container'}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
